package com.heyq.mybatis.mapper;

import com.heyq.mybatis.pojo.Emp;
import com.heyq.mybatis.pojo.EmpExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EmpMapper {
    /**
     * 通过条件获取当前的总记录数
     *
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emp
     *
     * @mbggenerated Sat Oct 15 16:56:32 CST 2022
     */
    int countByExample(EmpExample example);

    /**
     * 根据条件进行删除
     *
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emp
     *
     * @mbggenerated Sat Oct 15 16:56:32 CST 2022
     */
    int deleteByExample(EmpExample example);

    /**
     * 根据主键进行删除
     *
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emp
     *
     * @mbggenerated Sat Oct 15 16:56:32 CST 2022
     */
    int deleteByPrimaryKey(Integer empId);

    /**
     * 添加
     *
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emp
     *
     * @mbggenerated Sat Oct 15 16:56:32 CST 2022
     */
    int insert(Emp record);

    /**
     * 选择性添加
     *
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emp
     *
     * @mbggenerated Sat Oct 15 16:56:32 CST 2022
     */
    int insertSelective(Emp record);

    /**
     * 根据条件进行查询
     *
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emp
     *
     * @mbggenerated Sat Oct 15 16:56:32 CST 2022
     */
    List<Emp> selectByExample(EmpExample example);

    /**
     * 根据主键进行查询
     *
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emp
     *
     * @mbggenerated Sat Oct 15 16:56:32 CST 2022
     */
    Emp selectByPrimaryKey(Integer empId);

    /**
     * 根据条件选择性修改
     *
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emp
     *
     * @mbggenerated Sat Oct 15 16:56:32 CST 2022
     */
    int updateByExampleSelective(@Param("record") Emp record, @Param("example") EmpExample example);

    /**
     * 根据条件进行修改
     *
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emp
     *
     * @mbggenerated Sat Oct 15 16:56:32 CST 2022
     */
    int updateByExample(@Param("record") Emp record, @Param("example") EmpExample example);

    /**
     * 根据主键选择性修改
     *
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emp
     *
     * @mbggenerated Sat Oct 15 16:56:32 CST 2022
     */
    int updateByPrimaryKeySelective(Emp record);

    /**
     * 根据主键修改
     *
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emp
     *
     * @mbggenerated Sat Oct 15 16:56:32 CST 2022
     */
    int updateByPrimaryKey(Emp record);
}